### ISSUE TITLE
Allow `pathlib.Path`s in `args`

### ISSUE THREAD

**Issue by adamtheturtle** [thearchitector/subprocess-tee#1]
Thank you for this project!

`subprocess.run` allows `pathlib.Path`s in `args`, but to use `tee-subprocess` (in a type-safe manner) I have to convert paths to strings.

**Comment by thearchitector** [comment]
Thanks, and thanks for pointing that out. I can add definitely add path-like support

**Comment by thearchitector** [comment]
@adamtheturtle to clarify, you're talking about passing a `PathLike` object or a sequence containing a path-like (presumably as the first argument) into a non-shell invocation, correct?

**Comment by adamtheturtle** [comment]
Thank you @thearchitector for the response. Yes, that's right. Though, the "presumably" does not match my experience. For example, my code might look like:

```python
my_file = pathlib.Path("some_file.py")
tee_subprocess.run(args=["mypy", my_file])
```

FWIW my precise usage is at https://github.com/adamtheturtle/sybil-extras/blob/196162894a34112848656de997829a32a64b247a/src/sybil_extras/evaluators/shell_evaluator.py#L164.

**Comment by thearchitector** [comment]
@adamtheturtle I made a new [release](https://github.com/thearchitector/tee-subprocess/releases/tag/v1.1.0), which should cover your use case. I also (hopefully) improved the static typing quite a bit, so you should have better overloads when dealing with shell vs. non-shell invocations and text/binary outputs.

```sh
Python 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tee_subprocess import run
>>> from pathlib import Path
>>> run(["mypy", Path("./tee_subprocess/subprocess.py")])
Success: no issues found in 1 source file
CompletedProcess(args=['mypy', PosixPath('tee_subprocess/subprocess.py')], returncode=0
```

**Comment by adamtheturtle** [comment]
Fantastic, thank you!
